name: Run API Fetch Script

on:
  schedule:
    - cron: "10 11 * * *"   # Every day 4:40 PM IST (11:10 AM UTC)
  workflow_dispatch:        # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          DATABASE_URL: ${{ secrets.DB_URL }}
        run: python -m app.main
