name: Run API Fetch Script

on:
  schedule:
  - cron: "15 4 * * *"  # Every day at 9:45 AM IST (04:15 UTC)
  workflow_dispatch:        # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
           DB_URL: ${{ secrets.DB_URL }}
           MAIL_RECIPIENTS: ${{ secrets.MAIL_RECIPIENTS }}
           ADMIN_MAIL: ${{ secrets.ADMIN_MAIL }}
           NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
           SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
           SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: python -m app.main
